Fix requirements
automl/HPOlib1.5 pull request #34
Opened 2017-05-05 19:20 UTC by MechCoder

OpenML seems to be a requirement in openml_data_manager.py

2017-05-12 16:21 UTC, KEggensperger requested changes

2017-05-12 16:21 UTC, KEggensperger commented on hpolib/benchmarks/ml/svm_benchmark.py
> -from hpolib.util.openml_data_manager import OpenMLData
Removing that line will make the benchmark crash. Could you try/except the import error and print a message saying that you need openml-python in order to run some SVM benchmarks

2017-05-13 23:19 UTC, MechCoder commented on hpolib/benchmarks/ml/svm_benchmark.py
> -from hpolib.util.openml_data_manager import OpenMLData
Umm I don't see imports from OpenMLData being used anywhere in the `svm_benchmark` file. Where is it being used?

2017-05-13 23:19 UTC, MechCoder commented on requirements.txt
> +liac-arff
setup.py fails because

```
error: liac-arff 2.1.0 is installed but liac-arff>=2.1.1dev is required by {'openml'}
```

The latest version is 2.1.0 See: https://pypi.python.org/pypi/liac-arff . Do you have an idea about this?

2017-05-15 07:42 UTC, mfeurer commented on requirements.txt
> +liac-arff
Sorry, I don't have permissions to upgrade that package. You need to install it from github:

    pip install git+https://github.com/renatopp/liac-arff

@renatopp is it possible that you put the latest development version of liac-arff on pypi?

2017-05-15 07:56 UTC, KEggensperger approved these changes

2017-05-15 07:56 UTC, KEggensperger commented on hpolib/benchmarks/ml/svm_benchmark.py
> -from hpolib.util.openml_data_manager import OpenMLData
Sorry, my bad. OpenMLHoldoutDataManager is used for SvmOnVehicle and SvmOnCovertype. 

So, yes, you can remove that statement and I will open a issue on how to handle optional imports in benchmarks.

2017-08-03 21:55 UTC, amueller commented on requirements.txt
> +liac-arff
It's possibly to put a github version in requirements.txt, though it would really be better to put it on pypi so that ``pip install`` works for this (and openml).

2017-08-04 14:57 UTC, mfeurer commented on requirements.txt
> +liac-arff
I didn't have access to pypi+liac-arff, but that changed at some time in the last month. Anyway, that has changed and is correctly reflected in the development branch: https://github.com/automl/HPOlib2/blob/development/requirements.txt

Sorry for the inconvenience.

2018-09-12 15:22 UTC, KEggensperger commented
I guess this one is outdated, so I'll close it

2018-09-12 15:22 UTC, closed without merging