Crossvalidation
automl/HPOlib1.5 pull request #38
Opened 2017-05-23 12:01 UTC by KEggensperger

This PR adds a crossvalidation version of logistic regression and fixes some issues with the random seed.

2017-05-23 12:25 UTC, KEggensperger commented
This PR is now ready for reviewing
@aaronkl @mfeurer

2017-05-23 16:04 UTC, mfeurer requested changes

2017-05-23 16:04 UTC, mfeurer commented on .travis.yml
> +  #- curl https://raw.githubusercontent.com/automl/auto-sklearn/development/requirements.txt | xargs -n 1 -L 1 pip install
Does this imply that `auto-sklearn` should be an optional dependency?

2017-05-23 16:04 UTC, mfeurer commented on examples/SMAC3_on_LogisticRegression10CVOnMnist.py
> +logger = logging.getLogger("Optimizer")  # Enable to show Debug outputs
I don't see why one needs the `logger` variable.

2017-05-23 16:04 UTC, mfeurer commented on examples/SMAC3_on_LogisticRegression10CVOnMnist.py
> +                     "test_instances": ["10", ]
You don't need the comma in a list.

2017-05-23 16:04 UTC, mfeurer commented on examples/SMAC3_on_LogisticRegression10CVOnMnist.py
> +# Evaluate default config as a test
I don't understand the comment.

2017-05-23 16:04 UTC, mfeurer commented on examples/SMAC3_on_LogisticRegression10CVOnMnist.py
> +inc_value = taf.run(incumbent)[1]
Shouldn't that run on the test set?

2017-05-23 16:04 UTC, mfeurer commented on hpolib/benchmarks/ml/logistic_regression.py
> +        rng = kwargs.get("rng", None)
`None` is the default return value of `dict.get()` and not necessary.

2017-05-23 16:04 UTC, mfeurer commented on hpolib/benchmarks/ml/logistic_regression.py
> +        # if rng was not not, set rng for lasagne
two `not` in the comment

2017-05-23 16:04 UTC, mfeurer commented on hpolib/benchmarks/ml/logistic_regression.py
> +        :param config: list
shouldn't this be in numpy format?

2017-05-23 16:04 UTC, mfeurer commented on hpolib/benchmarks/ml/logistic_regression.py
> +        learning_rate = float(10 ** config[0])
I assume there was a reason why the values were casted to `np.float32` before this change request.

2017-05-23 16:04 UTC, mfeurer commented on hpolib/util/rng_helper.py
> +    :param rng: int or RandomState
Shouldn't this be in numpy docstyle format?

2017-05-23 16:04 UTC, mfeurer commented on hpolib/util/rng_helper.py
> +    :param rng: int or RandomState
Shouldn't this be in numpy docstyle format?

2017-05-23 16:04 UTC, mfeurer commented on setup.py
> +    install_requires=[],
why does this PR remove the requirements?

2017-05-24 09:09 UTC, KEggensperger commented on examples/SMAC3_on_LogisticRegression10CVOnMnist.py
> +# Evaluate default config as a test
Agreed and removed

2017-05-24 09:10 UTC, KEggensperger commented on examples/SMAC3_on_LogisticRegression10CVOnMnist.py
> +inc_value = taf.run(incumbent)[1]
Agreed and changed

2017-05-24 09:10 UTC, KEggensperger commented on examples/SMAC3_on_LogisticRegression10CVOnMnist.py
> +logger = logging.getLogger("Optimizer")  # Enable to show Debug outputs
Agreed and removed

2017-05-24 09:11 UTC, KEggensperger commented on .travis.yml
> +  #- curl https://raw.githubusercontent.com/automl/auto-sklearn/development/requirements.txt | xargs -n 1 -L 1 pip install
No, auto-sklearn is installed in l33 as a mandatory requirement

2017-05-24 09:12 UTC, KEggensperger commented on hpolib/benchmarks/ml/logistic_regression.py
> +        :param config: list
Not my code, but changed in anyway

2017-05-24 09:12 UTC, KEggensperger commented on hpolib/benchmarks/ml/logistic_regression.py
> +        # if rng was not not, set rng for lasagne
Agreed

2017-05-24 09:13 UTC, KEggensperger commented on hpolib/benchmarks/ml/logistic_regression.py
> +        learning_rate = float(10 ** config[0])
I don't know. @aaronkl: Is there a reason for this?

2017-05-24 09:22 UTC, KEggensperger commented on hpolib/util/rng_helper.py
> +    :param rng: int or RandomState
Agreed and changed it

2017-05-24 09:23 UTC, KEggensperger commented on setup.py
> +    install_requires=[],
Because the documentation recommends to install them independently and our current requirements.txt contains comments which breaks our current setup.py

2017-05-25 15:21 UTC, mfeurer approved these changes

2017-05-26 07:16 UTC, merged