ADD new surrogate benchmark for the exploring openml paper
automl/HPOlib1.5 pull request #65
Opened 2019-02-22 15:21 UTC by mfeurer

2019-03-05 14:28 UTC, mlindauer commented
Main problem:
```
module = importlib.import_module("hpolib.benchmarks.surrogates.exploring_openml")
benchmark = getattr(module, "XGBoost_3")(rng=seed)
```
Further issues:
 
- [ ] meta_information is missing (in particular `num_function_evals`, `name`, `f_opt` (can be set to 0))
- [ ] please remove the print statements

2019-03-05 16:06 UTC, mfeurer commented
I just updated the code a bit, the output of:
```
import importlib

module = importlib.import_module("hpolib.benchmarks.surrogates.exploring_openml")
benchmark = getattr(module, "XGBoost_3")(rng=1)
print(benchmark)
```
is now:
```
/home/feurerm/miniconda/3-4.5.4/envs/smac3/bin/python3 /home/feurerm/sync_dir/projects/HPOlib2/HPOlib2/bug.py
/home/feurerm/miniconda/3-4.5.4/envs/smac3/lib/python3.6/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/feurerm/miniconda/3-4.5.4/envs/smac3/lib/python3.6/site-packages/lightgbm/basic.py:1209: UserWarning: categorical_feature in Dataset is overridden.
New categorical_feature is [1]
  'New categorical_feature is {}'.format(sorted(list(categorical_feature))))
<hpolib.benchmarks.surrogates.exploring_openml.XGBoost_3 object at 0x7fd6f7f8cda0>

Process finished with exit code 0
```
It takes a while (~5 minutes) to build the surrogate, though.

2019-03-08 13:56 UTC, mlindauer commented
Now, it takes really a lot of time. I'm trying to import XGBoost_3 now for roughly half an hour. Unfortunately, there is not output and hence, I don't know what it is doing at all. Could you please some (sparse) output such that a user does not believe that he/she hits an infinite loop?

Is the reproducibility still ensured since the HPO runs every time again? So, can I validate the configuration I found on my local machine again and it will return the same results?

2019-03-12 08:39 UTC, KEggensperger requested changes
All in all this looks good, but I do have some minor comments?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +            Dataset Id as given in Table 2.
Table 2? Which Table 2 ...
Could you maybe add a list of valid ids in the meta_data?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +        if os.path.exists(surrogate_file_name):
If I run this benchmark once and then use n_splits=10 and I run it again with n_splits=5 will this update the surrogate?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +    def __init__(self, dataset_id, n_splits=10, rng=None):
Could you also add a rebuild flag? (related to my comment below)

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +        cs.seed(1)
This makes constructing the surrogate deterministic, correct?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +            if n_iterations > 40:
This should be an input with a default to the benchmark.

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +                self.logger.debug('Stopping random search due to good performance!')
Where do these numbers come from?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +        return {'function_value': y}
Is there no runtime we can return?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +            'f_opt': 0,
Are you sure about this?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +if __name__ == '__main__':
Why is this here?

2019-03-12 08:39 UTC, KEggensperger commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +            Dataset Id as given in Table 2.
Okay, I just found the list. So this is then rather an Abstract class that should not be used directly. Could you add that somewhere in the comments?

2019-03-12 20:30 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +            Dataset Id as given in Table 2.
Added this.

2019-03-12 20:30 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +        if os.path.exists(surrogate_file_name):
No.

2019-03-12 20:30 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +    def __init__(self, dataset_id, n_splits=10, rng=None):
Yes, I just added this.

2019-03-12 20:30 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +        cs.seed(1)
Correct.

2019-03-12 20:30 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +            if n_iterations > 40:
I added this, and also use it in the unit tests now.

2019-03-12 20:31 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +                self.logger.debug('Stopping random search due to good performance!')
I removed these numbers. These were based on intuition and the results your AAAI paper.

2019-03-12 20:31 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +        return {'function_value': y}
I just added the runtime.

2019-03-12 20:31 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +if __name__ == '__main__':
For some testing if all methods can be instantiated.

2019-03-13 08:13 UTC, mfeurer commented on hpolib/benchmarks/surrogates/exploring_openml.py
> +            'f_opt': 0,
I'd be happy to change this, but given the fact that the class is abstract I can't add a way to access the data and therefore need to assume the lowest possible value. I added two functions to retrieve the empirical min and max which is necessary to compute some metrics.

2019-03-13 08:14 UTC, mfeurer commented
Okay @KEggensperger I think I addressed all your requests.

2019-03-13 08:48 UTC, KEggensperger approved these changes

2019-03-13 09:08 UTC, merged