Classic control benchmark
automl/HPOlib1.5 pull request #74
Opened 2019-06-13 14:48 UTC by dekuenstle

Changes:

* Predefine reward thresholds of convergence criteria for the particular environment
* Use max episode timesteps predefined by the particular environment
* Use mean of episode rewards as run performance
* Log mean performance every 10th episode
* Command line interface for running default configuration

2019-09-16 11:16 UTC, KEggensperger commented
Are you still working on this? Just ping me when this is ready to be reviewed.

2019-09-16 13:43 UTC, dekuenstle commented
> Are you still working on this? Just ping me when this is ready to be reviewed.

I just resolved an issue with installation and added a useful feature. Work on this should be done for now.

2019-11-12 09:55 UTC, KEggensperger requested changes
This looks great! Before merging, I have 3 really minor requests:

- Could you please add a version string _0.2_ (as in https://github.com/automl/HPOlib2/blob/development/hpolib/benchmarks/ml/autosklearn_benchmark.py#L25) 
- Add your changelog (the text of this PR) as a comment in the code (e.g. as a _note_ in the meta-dictionary) so we know why this has been changed
- Remove the command line interface (no other benchmark has this). If you think the code is particular useful, feel free to move it to the example directory

I will then take care of this benchmark and see whether I can rebase this branch. Thanks a lot!

2019-11-12 09:55 UTC, KEggensperger commented on hpolib/benchmarks/rl/classic_control.py
Add a version string here

2019-11-12 09:55 UTC, KEggensperger commented on hpolib/benchmarks/rl/classic_control.py
> +if __name__ == '__main__':
Could you please remove this or move this example to the example directory?

2019-11-19 08:35 UTC, dekuenstle commented
> This looks great! Before merging, I have 3 really minor requests:
> 
> * Could you please add a version string _0.2_ (as in https://github.com/automl/HPOlib2/blob/development/hpolib/benchmarks/ml/autosklearn_benchmark.py#L25)
> * Add your changelog (the text of this PR) as a comment in the code (e.g. as a _note_ in the meta-dictionary) so we know why this has been changed
> * Remove the command line interface (no other benchmark has this). If you think the code is particular useful, feel free to move it to the example directory
> 
> I will then take care of this benchmark and see whether I can rebase this branch. Thanks a lot!

Thank you for the review! I changed according to your suggestions.

2019-11-19 10:04 UTC, KEggensperger approved these changes

2019-11-19 10:06 UTC, merged