Exploring OpenML surrogates: improve file locking to reduce overall lock time and file system access
automl/HPOlib1.5 pull request #79
Opened 2019-12-10 12:33 UTC by mfeurer

Running many of these experiments can result in a lot of time waiting for the file locks to be released. This PR implements the *it's easier to ask for forgiveness than for permission* pattern and iteratively tries to read a file instead of locking it first. Only if that fails it tries to lock the file. Also, constructing the surrogate is now done inside the file lock to avoid constructing the same surrogate multiple times. I'm not 100% sure if loading the file within the lock is still necessary, but it definitively won't hurt.

2019-12-10 15:14 UTC, KEggensperger approved these changes

2019-12-10 15:19 UTC, KEggensperger requested changes
Could you please run the unit-tests and make sure that the ones related to this benchmark don't crash:
```======================================================================

ERROR: test_random_config_exploring_openml (test_ml.test_random_config.TestRandomConfig)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/automl/HPOlib2/tests/test_ml/test_random_config.py", line 166, in test_random_config_exploring_openml

    y_opt = b.objective_function(f_opt)['function_value']

  File "/home/travis/build/automl/HPOlib2/hpolib/abstract_benchmark.py", line 79, in wrapper

    'into a ConfigSpace.Configuration object') from e

Exception: Error during the conversion of the provided into a ConfigSpace.Configuration object```

2019-12-11 11:14 UTC, mfeurer commented
I just fixed that test, thanks for noting.

2019-12-11 11:38 UTC, KEggensperger approved these changes

2019-12-11 11:40 UTC, merged